apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  index.html: |
    <html>
    <head>
      <title>ARGO CD</title>
    </head>
    <body>
      <h1>Welcome to Demo</h1>
      <p> Tanks yom </p>
    </body>
    </html>
